### ISSUE TITLE
External Link Error

### ISSUE THREAD

**Issue by spyworldxp** [zendtech/php-zendserver-docker#4]
I use percona database for multi container. So, I prefer to use external_links.
```
version: '2.0'
services:
    zend:
        image: php-zendserver:8.5
        ports:
            - 80:80
            - 10081:10081
            - 10082:10082
        volumes:
            - ./code/:/var/www/html/
        external_links:
            - percona
        environment:
            MYSQL_HOSTNAME: percona 
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: 123456
            ZS_ADMIN_PASSWORD: admin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 81:80
        external_links:
            - percona:db
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 123456
        network_mode: 'bridge'
```

This is the error message
```
zend_1        | Usage:
zend_1        | /usr/local/bin/nothing <mysql-hostname> <mysql-port> <mysql-username> <mysql-password> <mysql-db-name> <server-id> <web-api-key-name> <web-api-key>
zend_zend_1 exited with code 1
```
